"""
Trace Foundry - WAF Detector Module
Detects Web Application Firewalls via headers + fingerprinting
"""

import urllib.request
import urllib.error
from utils.display import print_section, ok, warn, info

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "body": ["cloudflare", "Attention Required! | Cloudflare"],
        "cookies": ["__cfduid", "cf_clearance"]
    },
    "AWS WAF / CloudFront": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop"],
        "body": ["aws", "Request blocked"],
        "cookies": []
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop"],
        "body": ["akamai", "Access Denied"],
        "cookies": ["ak_bmsc", "bm_sz"]
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": ["incapsula", "_incap_ses"],
        "cookies": ["incap_ses", "visid_incap"]
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "Access Denied - Sucuri Website Firewall"],
        "cookies": []
    },
    "ModSecurity": {
        "headers": ["mod_security", "modsecurity"],
        "body": ["mod_security", "ModSecurity", "This error was generated by Mod_Security"],
        "cookies": []
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "ts"],
        "body": ["The requested URL was rejected"],
        "cookies": ["TS", "BIGipServer"]
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "body": ["barracuda", "Barracuda Networks"],
        "cookies": ["barra_counter_session"]
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "fastly-restarts"],
        "body": [],
        "cookies": []
    },
}

class WAFModule:
    def __init__(self, domain, timeout=5):
        self.domain = domain
        self.timeout = timeout

    def run(self):
        print_section("WAF Detection")
        result = {"waf_detected": False, "waf_name": None, "evidence": []}

        urls = [f"https://{self.domain}", f"http://{self.domain}"]

        for url in urls:
            try:
                req = urllib.request.Request(url, headers={
                    "User-Agent": "Mozilla/5.0 (TraceFoundry/1.0) Security Research"
                })
                try:
                    response = urllib.request.urlopen(req, timeout=self.timeout)
                    headers = {k.lower(): v.lower() for k, v in response.headers.items()}
                    body = response.read(4096).decode("utf-8", errors="ignore").lower()
                    cookies = response.headers.get("Set-Cookie", "").lower()
                except urllib.error.HTTPError as e:
                    headers = {k.lower(): v.lower() for k, v in e.headers.items()}
                    try: body = e.read(4096).decode("utf-8", errors="ignore").lower()
                    except: body = ""
                    cookies = e.headers.get("Set-Cookie", "").lower()

                # Check each WAF signature
                for waf_name, sigs in WAF_SIGNATURES.items():
                    evidence = []
                    for h in sigs["headers"]:
                        if h.lower() in headers:
                            evidence.append(f"header:{h}")
                    for b in sigs["body"]:
                        if b.lower() in body:
                            evidence.append(f"body:{b}")
                    for c in sigs["cookies"]:
                        if c.lower() in cookies:
                            evidence.append(f"cookie:{c}")

                    if evidence:
                        result["waf_detected"] = True
                        result["waf_name"] = waf_name
                        result["evidence"] = evidence
                        ok(f"WAF Detected : {waf_name}")
                        info(f"Evidence     : {', '.join(evidence)}")
                        return result

                if not result["waf_detected"]:
                    warn("No WAF detected (or WAF is well-hidden)")
                break

            except Exception as e:
                warn(f"WAF check error: {e}")

        return result
